options:
  docker: true

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    master:
      - step:
          name: Build - Push - Deploy
          caches:
            - docker
          deployment: production
          script:
            # set image name
            - export IMAGE_NAME=registry.strawbinary.de/mb-sauna/website:latest

            # Docker Login
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.strawbinary.de

            # Build image
            - docker build -t $IMAGE_NAME --build-arg STRAPI_URL=$STRAPI_URL .

            # push image
            - docker push $IMAGE_NAME

            # deploy to server
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'mb-sauna'
                SERVER: 'vserver.strawbinary.de'
                COMMAND: '/home/mb-sauna/deploy.sh'
    develop:
      - step:
          name: Build - Push - Deploy (Development)
          caches:
            - docker
          deployment: staging
          script:
            # set image name
            - export IMAGE_NAME=registry.strawbinary.de/mb-sauna/website:dev

            # Docker Login
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.strawbinary.de

            # Build image
            - docker build -t $IMAGE_NAME --build-arg STRAPI_URL=$STRAPI_URL_DEV .

            # Push image
            - docker push $IMAGE_NAME

            # deploy to server
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: 'mb-sauna'
                SERVER: 'vserver.strawbinary.de'
                COMMAND: '/home/mb-sauna/dev/deploy.sh'
